### ISSUE TITLE
BDB Early-Game

### ISSUE THREAD

**Issue by DeltaDizzy** [KerbalKore/CWPT#1]
We should do this before BDB 1.7 so we have less to do when that happens.
## Able

- [x] Viklun-4688 Fairing Base
- [x] Viklun-100 LF Tank
- [x] Viklun-12 "Alpha" 
- [x] Viklun-12 "Alpha" B9 upgrades

## Ablestar

- [x] Fenris-4688 Fairing Base
- [x] Fenris-180 LF Tank
- [x] Fenris-18 "Alphastar"
- [x] Viklun-18 "Alphastar" B9 upgrades

## Agena A, B

- [x] Belle-70W LF Tank
- [x] Belle-A-25 "Hadar" engine
- [x] Belle probe core

## Atlas (SM68 and SLV-3C)

- [x] Base LF tank
- [x] Medium LF tank
- [x] Tapered LF tank
      Short tank? Is that mid-game? 
- [x] LR-89
- [x] LR-89 B9 upgrades

## Delta N

- [x] Dioscuri 2
- [x] Staara-37 

## Early Castors

- [x] Castor 1 and 2
- [x] Castor 4

## Redstone/SPARTA

- [x] Staara-31-III
- [x] Staara-10-LYC
- [x] Etoh-1400 LF Tank
- [x] Etoh-140 "Sandstone" LF Engine
- [x] Etoh-CS Control Surface

## Jupiter

- [x] HLR-291 "Vicenza" SRM
- [x] HLR-293 "Vicenza-3" SRM Cluster
- [x] HLR-VD11 0.625m Decoupler
- [x] HLR-2911 "Vicenza-11" SRM Cluster

## Thor

- [x] Fenris-860 Adapter tank
- [x] Fenris-880 LF tank
- [x] Fenris-360 LF tank
- [x] Fenris-215 "Odin" LF engine
- [x] Dioscuri for TAT
- [x] Staara-37BV PAM
- [x] Burner II

## Vanguard

- [x] STAR-20A
- [x] HLR-VD0 Stack Seperator
- [x] Viklun-625 Decoupler
- [x] Viklun-40 Adapter
- [x] Viklun-800 LF Tank
- [x] Fenris-TF Aerodynamic Fins
- [x] Viklun-50 Viking engine

**Comment by DeltaDizzy** [comment]
Would you count Atlas as early-game?

**Comment by KerbalKore** [comment]
yeah, the 1.5 stage bit lends itself well to early game

**Comment by KerbalKore** [comment]
the lighting all engines on the ground becomes very useful when using realfuels or engine ignitor

**Comment by KerbalKore** [comment]
Beginning work on techtagging them in the remove_yonge branch.

**Comment by DeltaDizzy** [comment]
@KerbalKore there is a branch specifically for these.

**Comment by KerbalKore** [comment]
alright, let me go and merge the changes into it.

**Comment by KerbalKore** [comment]
PR Made

**Comment by DeltaDizzy** [comment]
I could say so much about that but I will wait until later. How many of the above categories would you say are complete?

**Comment by KerbalKore** [comment]
The Able and Ablestar, early Thor stuff and Vangaurd. one or two SRBs are tagged as well. also, please go easy on me with the judgement, im not very good at either dev or working with other people.

**Comment by KerbalKore** [comment]
actually, @DeltaDizzy im going to temporarily revert the pull so more discussion can take place

**Comment by DeltaDizzy** [comment]
How much should we split up Delta? I'm leaning towards Thor-Delta (maybe split in half if there are enough parts to do so), Intermediate (Delta 0.1k-5k), Delta 6k (Delta II v1), Delta 7k (Delta II v2), and Delta 8k (Delta III).

**Comment by KerbalKore** [comment]
I like your thinking. Delta should probably get its own issue, so im gonna go make that

**Comment by KerbalKore** [comment]
Thor Delta of couse stays in earlygame

**Comment by KerbalKore** [comment]
I'm going to begin tagging the generic parts.

**Comment by DeltaDizzy** [comment]
Also, you should check the B9 upgrades to make sure they got done right.

**Comment by KerbalKore** [comment]
All are done
