### ISSUE TITLE
Delta

### ISSUE THREAD

**Issue by KerbalKore** [KerbalKore/CWPT#15]
## GEMs
- [x] GEM-40
- [x] GEM-40 Inline
- [x] GEM-46
- [x] GEM-60
- [x] GEM-60XL
## Delta-K stage
- [x] Avionics
- [x] Fairing (Delta P)
- [x] Fuel-Fairing (Delta K)
- [x] Tank
- [x] Engine Mount/RCS
- [x] AJ10-118K
- [x] Interstage
## Delta II
- [x] Upper tank
- [x] Lower tank
- [x] RS27
- [x] RS27A B9 Subtype
## Delta III (Intertwined with #4 until BDB gets its own DCSS)
- [x] Delta III Adapter tank
- [x] Fairing (Going to be part of a soon to be issue concerning generic parts)
- [x] DCSS (a scaled down +PART of the ReDirect DCSS if Redirect is installed)
- [x] BDB RL10B-2

**Comment by zorg2044** [comment]
Just a heads up the RS27A subtype is not linked to an upgrade. Its just there as a switch. The subtype was created for accuracy but there is no upgrade linked since the RS27A trades higher Isp and thrust for lower sea level Isp. So it isnt a straight up upgrade in all respects. It in fact has less thrust at sea level than the RS27 (by a small but noticeable amount).

If you wanted to place it somewhere specific you would need to patch in an upgrade into the subtype node or something.

**Comment by KerbalKore** [comment]
Thanks for the tip! Based on what I found online, the RS27A was used on Delta from 7000 up, while the normal RS27 was used on Delta on 2000, 3000, and 5000.
![image](https://user-images.githubusercontent.com/51207379/65529567-387cfd00-deab-11e9-949e-08c21f5f6098.png) Since we're going to need more Delta nodes anyway, I figure we can make an upgrade to unlock the RS27A in delta7k.

**Comment by KerbalKore** [comment]
@zorg2044 would this work to make the RS27A subtype require an upgrade?
```
%PARTUPGRADE[bluedog_delta]:FIRST:NEEDS[Bluedog_DB]
{
  name = bluedog_RS27A // RS27A
	partIcon = bluedog.Delta2.RS27
	techRequired = delta7k
	entryCost = 5000
	cost = 0 // for display only; all parts implementing this will need a PartStatsUpgradeModule with cost = this.

	title = Daleth-SSR-27a "Darkah" Liquid Engine
	basicInfo = <color=green>Max. Thrust (Vac.): 263.5 kN\nEngine Isp: 302 (Vac.)</color>
	manufacturer = Bluedog Design Bureau
	description = Upgrades the Daleth-SSR-27 "Darkah" Liquid Engine to the SSR-27A model.
}
@PART[bluedog_Delta2_RS27]:After[Bluedog_DB]
{
        @MODULE[ModuleB9PartSwitch]
        {
                @SUBTYPE[name[RS27A]]
                {
	             %upgradeRequired = bluedog_RS27A
                }
	}
}
```

**Comment by DeltaDizzy** [comment]
@KerbalKore so you are editing a PARTUPGRADE named `bluedog_delta`, and INSERTING a `name` key with value `bluedog_RS27A`

**Comment by KerbalKore** [comment]
yeah hold on I did a goof

**Comment by KerbalKore** [comment]
```
+PARTUPGRADE:FIRST:NEEDS[Bluedog_DB]
{
  name = bluedog_RS27A // RS27A
	partIcon = bluedog.Delta2.RS27
	techRequired = delta7k
	entryCost = 5000
	cost = 0 // for display only; all parts implementing this will need a PartStatsUpgradeModule with cost = this.

	title = Daleth-SSR-27a "Darkah" Liquid Engine
	basicInfo = <color=green>Max. Thrust (Vac.): 263.5 kN\nEngine Isp: 302 (Vac.)</color>
	manufacturer = Bluedog Design Bureau
	description = Upgrades the Daleth-SSR-27 "Darkah" Liquid Engine to the SSR-27A model.
}
@PART[bluedog_Delta2_RS27]:After[Bluedog_DB]
{
        @MODULE[ModuleB9PartSwitch]
        {
                @SUBTYPE[name[RS27A]]
                {
	             %upgradeRequired = bluedog_RS27A
                }
	}
}
```
would this work @DeltaDizzy @zorg2044 ?

**Comment by DeltaDizzy** [comment]
@KerbalKore which PARTUPGRADE are you copying?

**Comment by KerbalKore** [comment]
@DeltaDizzy I'm in class RN so i cant talk on discord, but im trying to make a new upgrade, and then make it so that the RS27A subtype requires that upgrade

**Comment by zorg2044** [comment]
It might work for the Rs27 but in general its a good idea to specify the module ID for B9 since a lot of parts might have multiple B9 switchers. It also makes your patch resilient against other types of B9 switchers being added to the part after the fact.

```
@PART[bluedog_Delta2_RS27]:After[Bluedog_DB]
{
        @MODULE[ModuleB9PartSwitch]:HAS[#moduleID[engineSwitch]]
        {
              ---snip---
	}
}

```

**Comment by DeltaDizzy** [comment]
Is it the GEM-60XL or the GEM-63XL?
