### ISSUE TITLE
Needed New Nodes

### ISSUE THREAD

**Issue by KerbalKore** [KerbalKore/CWPT#18]
## BDB
- [x] Atlas II
- [x] Atlas III
- [x] Centaur 2
- [x] Common Centaur/Centaur III
- [x] SLV-3X
- [x] Titan III
- [x] LDC
- [x] Incremental Delta
- [x] Delta 6000
- [x] Delta 7000
- [x] Delta 8000
- [x] Delta Upper Stages (for the AJ10 Varints and Delta-P fairing. Delta K leads from this)

**Comment by KerbalKore** [comment]
So i got some of the atlas and centaur nodes done, but the positioning has to change. Tonight I'll make a test install of KSP and try this out.

**Comment by KerbalKore** [comment]
AAAAND I JUST REALIZED I AM EDITING THE TREE.CFG IN MASTER AND NOT IN TREEFIXES

**Comment by KerbalKore** [comment]
![image](https://user-images.githubusercontent.com/51207379/65551676-42b4f080-ded7-11e9-84b6-5040642fac4d.png)

**Comment by KerbalKore** [comment]
![image](https://user-images.githubusercontent.com/51207379/65551720-64ae7300-ded7-11e9-8f44-ae9363d9d135.png)
hope is not lost

**Comment by KerbalKore** [comment]
![image](https://user-images.githubusercontent.com/51207379/65551748-76901600-ded7-11e9-87d8-9a582e7bcbf7.png)
Crisis averted

**Comment by KerbalKore** [comment]
I was also thinking about the tree design in general. Would it be more work to keep it in the style its in currently, or to make it something like this?
![image](https://user-images.githubusercontent.com/51207379/65554243-d5588e00-dedd-11e9-8887-4544934b7c34.png)
The design i just proposed would enable us to standardize node positions, thereby making it easier to add more nodes.

**Comment by KerbalKore** [comment]
Considering merging Early Aviation and Nazi Rocketry into one node, something like "Post-War Hardware" for those who want a rocket start instead of having to do planes

**Comment by KerbalKore** [comment]
So a bunch of the nodes are done, but they have a bad habit of breaking the game. #24

**Comment by DeltaDizzy** [comment]
Does Delta IV already have a node?

**Comment by KerbalKore** [comment]
@DeltaDizzy yes it does
