### ISSUE TITLE
Config Organization

### ISSUE THREAD

**Issue by DeltaDizzy** [KerbalKore/CWPT#2]
In [ProceduralFairings.cfg](https://github.com/KerbalKore/CWPT/blob/master/CWPT/ProceduralFairings.cfg) there are utility patches next to part patches next to part declarations, all kind of thrown together in a mess. If they don't get separated out, it would be good to at least document/organize the contents of configs. (If not the locations too)

**Comment by KerbalKore** [comment]
I would recommend ceasing the use of Yonge and  making a patch for each supported mod.

**Comment by KerbalKore** [comment]
Folder structure ex:
CWPT->
      ModSupport->
                         ModA->
                                PatchA
                                PatchB
                         ModB->
                                PatchA
                                PatchB

**Comment by DeltaDizzy** [comment]
so that would be this?
```
CWPT
  ModSupport
    ModA
      PatchA
      PatchB
    ModB
      PatchA
      PatchB
```

**Comment by KerbalKore** [comment]
that way we have less dependencies.

**Comment by KerbalKore** [comment]
Since this is being implemented, closing this issue.
