### ISSUE TITLE
SOCK Support

### ISSUE THREAD

**Issue by DeltaDizzy** [KerbalKore/CWPT#20]
## Shuttle Orbiter
- [x] OV-100 Payload Bay Docking Adapter
- [x] OV-100 Aft Fuselage Module
- [x] OV-100 Body Flap
- [x] OV-100 Delta Wing
- [x] OV-100 Outer Elevon
- [x] OV-100 Inner Elevon
- [x] OV-100 Forward Fuselage Module
- [x] OV-100 Ku Band Antenna
- [x] OV-100 Payload Bay Longeron Attachment Point
- [x] OV-100 Main Gear
- [x] OV-100 Mid Fuselage Section
- [x] OV-100 Nose Gear
- [x] OV-100 Payload Bay Structural Truss
- [x] OV-100 Vertical Stabilizer

## HabTech Robotics
- [x] KerboArm1 Latching End Effector
- [x] KerboArm1 Structural Boom Unit
- [x] KerboArm1 Elbow Servo Joint
- [x] KerboArm1 Servo Pitch Joint
- [x] KerboArm1 Axial Servo Joint
- [x] KerboArm2 Latching End Effector
- [x] KerboArm2 Structural Boom Unit
- [x] KerboArm2 General-Purpose Servo Joint
- [x] Power/Data Grapple Fixture

**Comment by KerbalKore** [comment]
done
