### ISSUE TITLE
BDB PR?

### ISSUE THREAD

**Issue by KerbalKore** [KerbalKore/CWPT#28]
Cobalt made a request that we make a pull to BDB that adds the tag to it, both for simplicity and a test of mod presupporting. Shall we begin this? @DeltaDizzy @zorg2044 @CobaltWolf

**Comment by DeltaDizzy** [comment]
I dont see why not. I already have a fork so i can start putting them in.

**Comment by KerbalKore** [comment]
@DeltaDizzy your branch is 345 commits behind, so around 100 or so parts is my guess. i would say we make a new fork.

**Comment by DeltaDizzy** [comment]
@KerbalKore you do realize i can just make a PR from BDB to my fork and update it, right?

**Comment by DeltaDizzy** [comment]
Agena is in, Apollo mapped out, will start Apollo later today. That begs the question though, @KerbalKore are all apollo parts tagged? (includes AARDV. LEM, Apollo blk. 1,2,3,4,5, docking lights)

**Comment by KerbalKore** [comment]
All the blocks are tagged, along with the LEM, but I'm and idiot and completely forgot about AARDV and the docking lights. I'll get on those. @DeltaDizzy

**Comment by KerbalKore** [comment]
AARDV and lights tagged @DeltaDizzy

**Comment by DeltaDizzy** [comment]
Also make sure you have Atlas and Centaur/Vega finished, as they are next. Atlas does not only include SM65, but also Muo, CELV, and Atlas I/II/III if they exist.

**Comment by KerbalKore** [comment]
I’ve tagged Muo and Atlas Sm65 through 3, but the node for atlas 1/2/3 aren’t finalized yet. I’ll try to make them work. CELV is not started yet, I’ll work on those today.

**Comment by KerbalKore** [comment]
Centaur is mostly tagged, but it’s nodes aren’t finished yet.

**Comment by DeltaDizzy** [comment]
As of now SLV-3X is in, and ALL Atlases have been scoped for the current PR. This includes CELV. In addition, I want to try and get the PRs finished by the 25th, as that is the current BDB 1.6.0 due date on that repo. Tagging is more important than nodes, as the tags (hopefully) wont need to shift around if the nodes change, and the tags are what go into BDB.

**Comment by DeltaDizzy** [comment]
@KerbalKore I dont quite get how you expect to PR into my BDB fork if yours is not a fork of mine or vice versa. They both branch off of Cobalts, but that is only useful when PRing to or from his.

**Comment by KerbalKore** [comment]
the pr is already open @DeltaDizzy.

**Comment by DeltaDizzy** [comment]
Titan is merged, now making checklist for Gemini/MOL. We probably can't get it in before Development -> master for 1.6.0, but maybe we can get it for 1.6.1 or 1.6.2.

**Comment by KerbalKore** [comment]
👍

**Comment by DeltaDizzy** [comment]
@KerbalKore Some gemini parts are not tagged (for now just the heatshields) In addition, there is BDB's Rumble Gemini. (aka small Big G, 1.875m Leo extension as opposed to 2.5) would that merit a new node? Current tag is "geminiplus"

**Comment by KerbalKore** [comment]
Hmm

**Comment by KerbalKore** [comment]
Geminiplus will be good for 1.0

**Comment by DeltaDizzy** [comment]
@KerbalKore C E A S E

**Comment by DeltaDizzy** [comment]
why not do the new branch -> squash into development -> merge to cobalt thing i told you about yesterday?

**Comment by KerbalKore** [comment]
uh

**Comment by KerbalKore** [comment]
because i forgot and am too far into the depths

**Comment by DeltaDizzy** [comment]
also your whitespace looks like a literal disease

**Comment by DeltaDizzy** [comment]
@KerbalKore not to be a dick but if you want me to be thorough I can be, re: readme pr

**Comment by KerbalKore** [comment]
please do

**Comment by KerbalKore** [comment]
i need advice from people with experience

**Comment by DeltaDizzy** [comment]
no longer an open question, we are doing this
