### ISSUE TITLE
Structuring idea

### ISSUE THREAD

**Issue by KerbalKore** [KerbalKore/CWPT#6]
A set of MM patches that on the :FIRST tag for example the BDB LR87-5 as `techtag = titan 2`
on the :FOR tag 
`
@PART:HAS[techtag=titan2]:FOR[CWPT]
{
         techrequired = titan2
}
`
and the :AFTER would remove the techtag field
:LAST would be saved for making precision adjustments

**Comment by KerbalKore** [comment]
@DeltaDizzy @IronCretin what do you think

**Comment by DeltaDizzy** [comment]
```
@PART[name]:FIRST:NEEDS[mod]
{
    techTag = x
}
```
```
@PART:HAS[#techtag[x]]:NEEDS[mod]
{
    @techRequired = y
}
```
@KerbalKore like this?

**Comment by KerbalKore** [comment]
@DeltaDizzy Yep.
Then:
```
@PART[name]:LAST:NEEDS[mod]
{
    !techtag[x]
}

**Comment by KerbalKore** [comment]
As well, BDB stuff will make this easier due to naming conventions.
ex:
```
@PART[bluedog_Titan2*]:FIRST:NEEDS:[BluedogDesignBureau]
{
    techtag = titan2
}

**Comment by DeltaDizzy** [comment]
Wait why are we deleting the tag?

**Comment by KerbalKore** [comment]
For cleanliness. in RO they use a similiar system and delete the tags afterwards to avoid issues

**Comment by KerbalKore** [comment]
Now that this is being implemented, I’m closing this issue
