### ISSUE TITLE
Constructive Criticisms

### ISSUE THREAD

**Issue by DeltaDizzy** [KerbalKore/CWPT#8]
## Changes required to make it functional

* `NEEDS[BluedogDesignBureau]` should be changed to `NEEDS[Bluedog_DB]` 
* `@techtag` should be changed to `techtag` or `%techtag` unless they are inserted into every part before the support patches run.

## Style 
`CWPT/CWPT/ModSupport/BDB/BDB,cfg` Why have a folder for BDB if it will only have one file? It may be better to split part families into their own files. i.e. Titan.cfg, Apollo.cfg, Saturn.cfg, Gemini.cfg, etc.

**Comment by KerbalKore** [comment]
Good idea. I’ll do those when I get home from school.

**Comment by KerbalKore** [comment]
Done.

**Comment by DeltaDizzy** [comment]
But is Titan III still tagged as Titan II?

**Comment by KerbalKore** [comment]
there was no titan III node, so I figured the Titan 3 stuff should be stored in Titan 2 until we get to nodes
